import { WeeklyOutfitPlan } from '@/types'

export const mockWeeklyPlan: WeeklyOutfitPlan = {
  overallConcept:
    'モノトーンをベースに、素材感とシルエットで差をつけるミニマルスタイルの1週間。',
  outfits: [
    {
      day: '月曜日',
      dayEn: 'MON',
      theme: 'クリーンモノトーン',
      mood: 'スッキリ・都会的',
      stylingTip: '白シャツはタックインしてシャープな印象に。',
      items: [
        {
          category: 'トップス',
          name: 'オックスフォードシャツ レギュラーフィット',
          brand: 'Graphpaper',
          price: 22000,
          description: 'コットン100% 広幅オックス',
          color: 'ホワイト',
          searchQuery: 'Graphpaper oxford shirt white',
          searchUrl: 'https://zozo.jp/search/?q=グラフペーパー+オックスフォードシャツ+ホワイト',
          imageColor: '#F5F5F5',
        },
        {
          category: 'ボトムス',
          name: 'スリムテーパードアンクルパンツ',
          brand: 'Comoli',
          price: 28600,
          description: 'ウール混 上品なドレープ',
          color: 'ブラック',
          searchQuery: 'Comoli tapered pants black',
          searchUrl: 'https://zozo.jp/search/?q=コモリ+テーパードパンツ+ブラック',
          imageColor: '#1A1A1A',
        },
        {
          category: 'シューズ',
          name: 'チャッカブーツ',
          brand: 'Dr. Martens',
          price: 22000,
          description: 'スムースレザー 3ホール',
          color: 'ブラック',
          searchQuery: 'Dr Martens chukka boots black',
          searchUrl: 'https://zozo.jp/search/?q=ドクターマーチン+チャッカブーツ+ブラック',
          imageColor: '#111111',
        },
        {
          category: 'バッグ',
          name: 'トートバッグ',
          brand: 'Auralee',
          price: 18700,
          description: 'ヘビーキャンバス ミニマル',
          color: 'ブラック',
          searchQuery: 'Auralee tote bag black',
          searchUrl: 'https://zozo.jp/search/?q=オーラリー+トートバッグ+ブラック',
          imageColor: '#222222',
        },
      ],
    },
    {
      day: '火曜日',
      dayEn: 'TUE',
      theme: 'ネイビーエレガンス',
      mood: 'クール・上品',
      stylingTip: 'ネイビーニットにベージュパンツで温かみをプラス。',
      items: [
        {
          category: 'トップス',
          name: 'メリノウールクルーネックセーター',
          brand: 'nanamica',
          price: 24200,
          description: 'ウール100% さらりと上品',
          color: 'ネイビー',
          searchQuery: 'nanamica merino crewneck navy',
          searchUrl: 'https://zozo.jp/search/?q=ナナミカ+クルーネックセーター+ネイビー',
          imageColor: '#1A237E',
        },
        {
          category: 'ボトムス',
          name: 'テーパードチノパンツ',
          brand: 'A.P.C.',
          price: 21000,
          description: 'コットンチノ フランスブランド',
          color: 'ベージュ',
          searchQuery: 'APC chino pants beige tapered',
          searchUrl: 'https://zozo.jp/search/?q=アーペーセー+チノパンツ+ベージュ',
          imageColor: '#C8A882',
        },
        {
          category: 'シューズ',
          name: 'スエードペニーローファー',
          brand: 'Tod\'s',
          price: 58300,
          description: 'スエード 本革底 イタリア製',
          color: 'タン',
          searchQuery: "Tod's suede penny loafer tan",
          searchUrl: 'https://zozo.jp/search/?q=トッズ+ローファー+タン',
          imageColor: '#C19A6B',
        },
      ],
    },
    {
      day: '水曜日',
      dayEn: 'WED',
      theme: 'グレートーン レイヤード',
      mood: 'カジュアル・こなれ',
      stylingTip: 'グレーのグラデーションでまとめると洗練された印象に。',
      items: [
        {
          category: 'アウター',
          name: 'コーチジャケット',
          brand: 'Carhartt WIP',
          price: 18700,
          description: 'コットンナイロン リップストップ',
          color: 'ライトグレー',
          searchQuery: 'Carhartt WIP coach jacket gray',
          searchUrl: 'https://zozo.jp/search/?q=カーハート+コーチジャケット+グレー',
          imageColor: '#BDBDBD',
        },
        {
          category: 'トップス',
          name: 'ヘビーウェイトTシャツ',
          brand: 'Champion',
          price: 4400,
          description: '厚手コットン USA製',
          color: 'チャコール',
          searchQuery: 'Champion heavyweight tshirt charcoal',
          searchUrl: 'https://zozo.jp/search/?q=チャンピオン+ヘビーウェイト+Tシャツ+チャコール',
          imageColor: '#555555',
        },
        {
          category: 'ボトムス',
          name: 'ワイドストレートデニム 550',
          brand: 'Levi\'s',
          price: 9900,
          description: '12oz デニム リラックスフィット',
          color: 'ミッドグレー',
          searchQuery: "Levi's 550 wide straight denim gray",
          searchUrl: 'https://zozo.jp/search/?q=リーバイス+ワイドデニム+グレー',
          imageColor: '#9E9E9E',
        },
        {
          category: 'シューズ',
          name: '992 スニーカー',
          brand: 'New Balance',
          price: 17600,
          description: 'ENCAP クッション Made in USA',
          color: 'グレー',
          searchQuery: 'New Balance 992 sneaker gray',
          searchUrl: 'https://zozo.jp/search/?q=ニューバランス+992+グレー',
          imageColor: '#ADADAD',
        },
      ],
    },
    {
      day: '木曜日',
      dayEn: 'THU',
      theme: 'アーバンストリート',
      mood: 'エッジ・スポーティ',
      stylingTip: 'ハーフジップはオープンで着て首元を演出。',
      items: [
        {
          category: 'トップス',
          name: 'ハーフジップスウェット',
          brand: 'STÜSSY',
          price: 13200,
          description: 'フレンチテリー ロゴ刺繍',
          color: 'オフホワイト',
          searchQuery: 'Stussy half zip sweatshirt off white',
          searchUrl: 'https://zozo.jp/search/?q=ステューシー+ハーフジップスウェット+オフホワイト',
          imageColor: '#FAF5EB',
        },
        {
          category: 'ボトムス',
          name: 'ナイロンカーゴパンツ',
          brand: 'Patagonia',
          price: 14300,
          description: 'リップストップナイロン 撥水',
          color: 'オリーブ',
          searchQuery: 'Patagonia nylon cargo pants olive',
          searchUrl: 'https://zozo.jp/search/?q=パタゴニア+カーゴパンツ+オリーブ',
          imageColor: '#6B7C50',
        },
        {
          category: 'シューズ',
          name: 'サロモン スニーカー XT-6',
          brand: 'Salomon',
          price: 22000,
          description: 'トレイルランシューズ タウン仕様',
          color: 'ブラック',
          searchQuery: 'Salomon XT-6 sneaker black',
          searchUrl: 'https://zozo.jp/search/?q=サロモン+XT-6+ブラック',
          imageColor: '#212121',
        },
      ],
    },
    {
      day: '金曜日',
      dayEn: 'FRI',
      theme: 'スマートカジュアル TGIF',
      mood: 'リラックス・洗練',
      stylingTip: 'テーラードジャケット×デニムで週末感を演出。',
      items: [
        {
          category: 'アウター',
          name: 'アンコンブレザー',
          brand: 'Margaret Howell',
          price: 77000,
          description: 'ウールギャバ 英国スタイル',
          color: 'ライトグレー',
          searchQuery: 'Margaret Howell uncon blazer light gray',
          searchUrl: 'https://zozo.jp/search/?q=マーガレットハウエル+ブレザー+ライトグレー',
          imageColor: '#CFD8DC',
        },
        {
          category: 'トップス',
          name: 'モックネック長袖Tシャツ',
          brand: 'UNIQLO',
          price: 2990,
          description: 'コットンモーダル混 なめらか',
          color: 'ホワイト',
          searchQuery: 'UNIQLO mock neck long sleeve tee white',
          searchUrl: 'https://zozo.jp/search/?q=ユニクロ+モックネック+長袖+ホワイト',
          imageColor: '#FFFFFF',
        },
        {
          category: 'ボトムス',
          name: 'セルビッジスリムデニム',
          brand: 'Nudie Jeans',
          price: 24200,
          description: 'オーガニックコットン スウェーデン製',
          color: 'インディゴ',
          searchQuery: 'Nudie Jeans slim selvedge denim indigo',
          searchUrl: 'https://zozo.jp/search/?q=ヌーディージーンズ+スリムデニム+インディゴ',
          imageColor: '#283593',
        },
        {
          category: 'シューズ',
          name: 'ローカットレザースニーカー',
          brand: 'Common Projects',
          price: 66000,
          description: 'カーフレザー イタリア製',
          color: 'ホワイト',
          searchQuery: 'Common Projects leather sneaker white',
          searchUrl: 'https://zozo.jp/search/?q=コモンプロジェクト+スニーカー+ホワイト',
          imageColor: '#FAFAFA',
        },
      ],
    },
    {
      day: '土曜日',
      dayEn: 'SAT',
      theme: 'アースカラー ウィークエンド',
      mood: 'ナチュラル・リラックス',
      stylingTip: 'ブラウン系でまとめて土っぽいあたたかみを。',
      items: [
        {
          category: 'トップス',
          name: 'フランネルオーバーシャツ',
          brand: 'Engineered Garments',
          price: 24200,
          description: 'コットンフランネル ネイティブチェック',
          color: 'ブラウンチェック',
          searchQuery: 'Engineered Garments flannel overshirt brown check',
          searchUrl: 'https://zozo.jp/search/?q=エンジニアードガーメンツ+フランネルシャツ+ブラウン',
          imageColor: '#795548',
        },
        {
          category: 'ボトムス',
          name: 'リラックスコーデュロイパンツ',
          brand: 'GRAMICCI',
          price: 11000,
          description: 'コーデュロイ ガゼットクロッチ',
          color: 'キャメル',
          searchQuery: 'Gramicci corduroy pants camel',
          searchUrl: 'https://zozo.jp/search/?q=グラミチ+コーデュロイパンツ+キャメル',
          imageColor: '#C49A3C',
        },
        {
          category: 'シューズ',
          name: 'ビルケンシュトック ボストン',
          brand: 'Birkenstock',
          price: 18700,
          description: 'スエードレザー フットベッド',
          color: 'タン',
          searchQuery: 'Birkenstock Boston suede tan',
          searchUrl: 'https://zozo.jp/search/?q=ビルケンシュトック+ボストン+タン',
          imageColor: '#A0784A',
        },
        {
          category: 'バッグ',
          name: 'デイパック',
          brand: 'and wander',
          price: 19800,
          description: 'X-PAC 超軽量 山岳デザイン',
          color: 'ナチュラル',
          searchQuery: 'and wander daypack natural',
          searchUrl: 'https://zozo.jp/search/?q=アンドワンダー+デイパック',
          imageColor: '#E8D5B7',
        },
      ],
    },
    {
      day: '日曜日',
      dayEn: 'SUN',
      theme: 'オールブラック サンデー',
      mood: 'エレガント・モード',
      stylingTip: 'テクスチャーの違う黒を重ねて奥行きを出して。',
      items: [
        {
          category: 'トップス',
          name: 'ニットポロシャツ',
          brand: 'Ami Paris',
          price: 46200,
          description: 'コットンニット フランス製',
          color: 'ブラック',
          searchQuery: 'Ami Paris knit polo shirt black',
          searchUrl: 'https://zozo.jp/search/?q=アミパリス+ニットポロ+ブラック',
          imageColor: '#0D0D0D',
        },
        {
          category: 'ボトムス',
          name: 'テーパードトラウザー',
          brand: 'Toteme',
          price: 36300,
          description: 'ウールブレンド ドレープ感',
          color: 'ブラック',
          searchQuery: 'Toteme tapered trousers black wool',
          searchUrl: 'https://zozo.jp/search/?q=トーテム+テーパードトラウザー+ブラック',
          imageColor: '#1C1C1C',
        },
        {
          category: 'シューズ',
          name: 'サイドゴアブーツ スクエアトゥ',
          brand: 'ZARA',
          price: 11990,
          description: 'スクエアトゥ ブロックヒール',
          color: 'ブラック',
          searchQuery: 'ZARA square toe side gore boots black',
          searchUrl: 'https://zozo.jp/search/?q=サイドゴアブーツ+スクエアトゥ+ブラック',
          imageColor: '#080808',
        },
        {
          category: 'アクセサリー',
          name: 'シルバーチェーンネックレス',
          brand: 'Maison Margiela',
          price: 28600,
          description: 'スターリングシルバー 細チェーン',
          color: 'シルバー',
          searchQuery: 'Maison Margiela silver chain necklace thin',
          searchUrl: 'https://zozo.jp/search/?q=マルジェラ+シルバーチェーンネックレス',
          imageColor: '#C0C0C0',
        },
      ],
    },
  ],
}
