export type Platform = 'instagram' | 'tiktok' | 'x'

export interface Trend {
  id: string
  tag: string          // #タグ名
  label: string        // 表示名
  platform: Platform
  category: string     // スタイルカテゴリ
  description: string  // 一言説明
  count: string        // 投稿数
  countNum: number     // ソート用
  rising: boolean      // 急上昇中
  accentColor: string  // カードアクセントカラー
}

export const PLATFORM_META: Record<Platform, { name: string; color: string; bg: string }> = {
  instagram: { name: 'Instagram', color: '#C13584', bg: '#FDF0F8' },
  tiktok:    { name: 'TikTok',    color: '#EE1D52', bg: '#FFF0F3' },
  x:         { name: 'X',         color: '#000000', bg: '#F5F5F5' },
}

export const TRENDS: Trend[] = [
  // ── Instagram ──
  {
    id: 'gorpcore',
    tag: '#ゴープコア',
    label: 'ゴープコア',
    platform: 'instagram',
    category: 'アウトドア系',
    description: 'アウトドアギアをタウンに落とし込む',
    count: '128K',
    countNum: 128000,
    rising: true,
    accentColor: '#6B7C50',
  },
  {
    id: 'old-money',
    tag: '#オールドマネー',
    label: 'オールドマネー',
    platform: 'instagram',
    category: 'ラグジュアリー系',
    description: '上品なクラシックとエレガンスの融合',
    count: '94K',
    countNum: 94000,
    rising: false,
    accentColor: '#C8A882',
  },
  {
    id: 'clean-girl',
    tag: '#クリーンガール',
    label: 'クリーンガール',
    platform: 'instagram',
    category: 'ミニマル系',
    description: 'シンプルで清潔感あふれる洗練スタイル',
    count: '203K',
    countNum: 203000,
    rising: true,
    accentColor: '#F5F5F0',
  },
  {
    id: 'preppy',
    tag: '#プレッピー',
    label: 'プレッピー',
    platform: 'instagram',
    category: 'クラシック系',
    description: 'アイビーリーグ発のクリーンスタイル',
    count: '67K',
    countNum: 67000,
    rising: false,
    accentColor: '#1A237E',
  },
  {
    id: 'monotone',
    tag: '#モノトーンコーデ',
    label: 'モノトーンコーデ',
    platform: 'instagram',
    category: 'ミニマル系',
    description: '白・黒・グレーで統一した都会的スタイル',
    count: '312K',
    countNum: 312000,
    rising: false,
    accentColor: '#424242',
  },
  // ── TikTok ──
  {
    id: 'y2k',
    tag: '#Y2Kファッション',
    label: 'Y2Kファッション',
    platform: 'tiktok',
    category: 'レトロ系',
    description: '2000年代のポップでキラキラな着こなし',
    count: '445K',
    countNum: 445000,
    rising: true,
    accentColor: '#E91E8C',
  },
  {
    id: 'balletcore',
    tag: '#バレエコア',
    label: 'バレエコア',
    platform: 'tiktok',
    category: 'フェミニン系',
    description: 'バレリーナにインスパイアされた優雅スタイル',
    count: '89K',
    countNum: 89000,
    rising: true,
    accentColor: '#F8BBD0',
  },
  {
    id: 'korean-fit',
    tag: '#韓国コーデ',
    label: '韓国コーデ',
    platform: 'tiktok',
    category: 'K-Fashion',
    description: 'K-POPアイドルからインスパイアされた最新トレンド',
    count: '567K',
    countNum: 567000,
    rising: false,
    accentColor: '#BF0000',
  },
  {
    id: 'cottagecore',
    tag: '#コテージコア',
    label: 'コテージコア',
    platform: 'tiktok',
    category: 'ナチュラル系',
    description: '田舎風ロマンティック＆自然派スタイル',
    count: '34K',
    countNum: 34000,
    rising: false,
    accentColor: '#8D6E63',
  },
  {
    id: 'dad-sneaker',
    tag: '#ダッドスニーカー',
    label: 'ダッドスニーカー',
    platform: 'tiktok',
    category: 'スポーツ系',
    description: 'ゴツめのスポーツシューズをメインにしたコーデ',
    count: '156K',
    countNum: 156000,
    rising: true,
    accentColor: '#1565C0',
  },
  // ── X ──
  {
    id: 'daily-coord',
    tag: '#今日のコーデ',
    label: '今日のコーデ',
    platform: 'x',
    category: 'カジュアル系',
    description: '日常コーデの報告・共有タグ',
    count: '1.2M',
    countNum: 1200000,
    rising: false,
    accentColor: '#111111',
  },
  {
    id: 'uniqlo-coord',
    tag: '#ユニクロコーデ',
    label: 'ユニクロコーデ',
    platform: 'x',
    category: 'プチプラ系',
    description: 'UNIQLOアイテムを主役にした着回しコーデ',
    count: '890K',
    countNum: 890000,
    rising: false,
    accentColor: '#E60012',
  },
  {
    id: 'sustainable',
    tag: '#サステナブルファッション',
    label: 'サステナブル',
    platform: 'x',
    category: 'エシカル系',
    description: '環境に配慮した素材・古着・長く使えるコーデ',
    count: '45K',
    countNum: 45000,
    rising: true,
    accentColor: '#2E7D32',
  },
  {
    id: 'vintage',
    tag: '#ヴィンテージ古着',
    label: 'ヴィンテージ古着',
    platform: 'x',
    category: 'ヴィンテージ系',
    description: '古着ミックスで個性を出すスタイル',
    count: '234K',
    countNum: 234000,
    rising: false,
    accentColor: '#795548',
  },
  {
    id: 'minimalist',
    tag: '#ミニマリストファッション',
    label: 'ミニマリスト',
    platform: 'x',
    category: 'ミニマル系',
    description: '必要最低限のアイテムで組む洗練スタイル',
    count: '178K',
    countNum: 178000,
    rising: true,
    accentColor: '#9E9E9E',
  },
]
